spring.application.name=ParkingLot

spring.datasource.url=jdbc:postgresql://localhost:5432/parkingdb
spring.datasource.username=postgres
spring.datasource.password=2105

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
logging.level.org.flywaydb=DEBUG

