-- V2__seed_parking_slots.sql

INSERT INTO parking_slot
(slot_number, floor_number, vehicle_type, slot_status)
VALUES

-- FLOOR 1 : 10 TRUCK SLOTS
('T1', 1, 'TRUCK', 'FREE'),
('T2', 1, 'TRUCK', 'FREE'),
('T3', 1, 'TRUCK', 'FREE'),
('T4', 1, 'TRUCK', 'FREE'),
('T5', 1, 'TRUCK', 'FREE'),
('T6', 1, 'TRUCK', 'FREE'),
('T7', 1, 'TRUCK', 'FREE'),
('T8', 1, 'TRUCK', 'FREE'),
('T9', 1, 'TRUCK', 'FREE'),
('T10', 1, 'TRUCK', 'FREE'),

-- FLOOR 2 : 20 BIKE + 10 CAR
('B1', 2, 'BIKE', 'FREE'),
('B2', 2, 'BIKE', 'FREE'),
('B3', 2, 'BIKE', 'FREE'),
('B4', 2, 'BIKE', 'FREE'),
('B5', 2, 'BIKE', 'FREE'),
('B6', 2, 'BIKE', 'FREE'),
('B7', 2, 'BIKE', 'FREE'),
('B8', 2, 'BIKE', 'FREE'),
('B9', 2, 'BIKE', 'FREE'),
('B10', 2, 'BIKE', 'FREE'),
('B11', 2, 'BIKE', 'FREE'),
('B12', 2, 'BIKE', 'FREE'),
('B13', 2, 'BIKE', 'FREE'),
('B14', 2, 'BIKE', 'FREE'),
('B15', 2, 'BIKE', 'FREE'),
('B16', 2, 'BIKE', 'FREE'),
('B17', 2, 'BIKE', 'FREE'),
('B18', 2, 'BIKE', 'FREE'),
('B19', 2, 'BIKE', 'FREE'),
('B20', 2, 'BIKE', 'FREE'),

('C1', 2, 'CAR', 'FREE'),
('C2', 2, 'CAR', 'FREE'),
('C3', 2, 'CAR', 'FREE'),
('C4', 2, 'CAR', 'FREE'),
('C5', 2, 'CAR', 'FREE'),
('C6', 2, 'CAR', 'FREE'),
('C7', 2, 'CAR', 'FREE'),
('C8', 2, 'CAR', 'FREE'),
('C9', 2, 'CAR', 'FREE'),
('C10', 2, 'CAR', 'FREE'),

-- FLOOR 3 : 20 BIKE + 10 CAR
('B21', 3, 'BIKE', 'FREE'),
('B22', 3, 'BIKE', 'FREE'),
('B23', 3, 'BIKE', 'FREE'),
('B24', 3, 'BIKE', 'FREE'),
('B25', 3, 'BIKE', 'FREE'),
('B26', 3, 'BIKE', 'FREE'),
('B27', 3, 'BIKE', 'FREE'),
('B28', 3, 'BIKE', 'FREE'),
('B29', 3, 'BIKE', 'FREE'),
('B30', 3, 'BIKE', 'FREE'),
('B31', 3, 'BIKE', 'FREE'),
('B32', 3, 'BIKE', 'FREE'),
('B33', 3, 'BIKE', 'FREE'),
('B34', 3, 'BIKE', 'FREE'),
('B35', 3, 'BIKE', 'FREE'),
('B36', 3, 'BIKE', 'FREE'),
('B37', 3, 'BIKE', 'FREE'),
('B38', 3, 'BIKE', 'FREE'),
('B39', 3, 'BIKE', 'FREE'),
('B40', 3, 'BIKE', 'FREE'),

('C11', 3, 'CAR', 'FREE'),
('C12', 3, 'CAR', 'FREE'),
('C13', 3, 'CAR', 'FREE'),
('C14', 3, 'CAR', 'FREE'),
('C15', 3, 'CAR', 'FREE'),
('C16', 3, 'CAR', 'FREE'),
('C17', 3, 'CAR', 'FREE'),
('C18', 3, 'CAR', 'FREE'),
('C19', 3, 'CAR', 'FREE'),
('C20', 3, 'CAR', 'FREE'),

-- FLOOR 4 : 20 BIKE + 10 CAR
('B41', 4, 'BIKE', 'FREE'),
('B42', 4, 'BIKE', 'FREE'),
('B43', 4, 'BIKE', 'FREE'),
('B44', 4, 'BIKE', 'FREE'),
('B45', 4, 'BIKE', 'FREE'),
('B46', 4, 'BIKE', 'FREE'),
('B47', 4, 'BIKE', 'FREE'),
('B48', 4, 'BIKE', 'FREE'),
('B49', 4, 'BIKE', 'FREE'),
('B50', 4, 'BIKE', 'FREE'),
('B51', 4, 'BIKE', 'FREE'),
('B52', 4, 'BIKE', 'FREE'),
('B53', 4, 'BIKE', 'FREE'),
('B54', 4, 'BIKE', 'FREE'),
('B55', 4, 'BIKE', 'FREE'),
('B56', 4, 'BIKE', 'FREE'),
('B57', 4, 'BIKE', 'FREE'),
('B58', 4, 'BIKE', 'FREE'),
('B59', 4, 'BIKE', 'FREE'),
('B60', 4, 'BIKE', 'FREE'),

('C21', 4, 'CAR', 'FREE'),
('C22', 4, 'CAR', 'FREE'),
('C23', 4, 'CAR', 'FREE'),
('C24', 4, 'CAR', 'FREE'),
('C25', 4, 'CAR', 'FREE'),
('C26', 4, 'CAR', 'FREE'),
('C27', 4, 'CAR', 'FREE'),
('C28', 4, 'CAR', 'FREE'),
('C29', 4, 'CAR', 'FREE'),
('C30', 4, 'CAR', 'FREE');